# Generated by Django 2.0.5 on 2018-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_biller_billerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billerprofile',
            name='biller_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='billerprofile',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
