# Generated by Django 2.0.5 on 2018-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180710_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('biller_name', models.CharField(max_length=25)),
                ('biller_ref', models.CharField(blank=True, max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
